### PR TITLE
Update to ES6

### PR DESCRIPTION
**Pull request by TomFrost**

### CODE REVIEW

**Comment by MarkHerhold** [comment]
Is this simply a rewrite or are there breaking changes?

**Comment by TomFrost** [comment]
Not a rewrite (in the functional sense; git logs it that way since every line changed) -- just bringing it up to speed with new style guidelines and ES6 syntax before I implement more 1.0.0 changes. At this point the only breaking change is dropping 0.12 compatability, so this won't be pushed out until 1.0.

**Comment by MarkHerhold** [comment]
Ok, excellent! I'll all for dropping old versions of node.js and using ES6 features! :+1:

**Comment by TomFrost** [comment]
Amen. I've been systematically working through all my libs and converting over. It's a huge pain, but totally liberating. Especially for the ones that used to use Babel, and no longer need it!

**Comment by MarkHerhold** [comment]
@TomFrost Are you going to publish a version of Bristol with these changes? Perhaps a `npm version preminor`?

**Pull request merged**
